on:
  schedule:
    - cron:  '* * * * *'
  repository_dispatch:
    types: 
      - ping
      - repo_create
jobs:
  ping:
    if: ${{ github.event.action == 'ping' }}
    runs-on: ubuntu-latest
    steps:
      - name: Ping
        run: "Response acknowledged 200!"
  repo-create:
    if: ${{ github.event.action == 'repo-create' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update branch protection
        uses: Hatzelencio/branch-protection@v1.0.0
        env:
          GITHUB_TOKEN: ${{secrets.ACCESS_TOKEN}}
